### ISSUE TITLE
Importing some components works but others fail

### ISSUE THREAD

**Issue by pojntfx** [vanilla-framework/vanilla-framework-react#122] opened 2018-03-12 17:35 UTC
After debugging for quite some time now, I'm still not sure whether I'm doing anything wrong, but importing some components does not seem to work while others do.
Following the CRA example I can render a button:
```js
import React, { Component } from "react";

// Components
import { Button } from "vanilla-framework-react";

export default class PageNotFound extends Component {
  render() {
    return <Button value="Test"/>;
  }
}
```

But when I try to render a notification:
```js
import React, { Component } from "react";

// Components
import { Notification } from "vanilla-framework-react";

export default class PageNotFound extends Component {
  render() {
    return <Notification>Page has not been found!</Notification>;
  }
}
```

it fails with the following error:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PageNotFound`.
```
Is there something I'm doing wrong? Is this a bug? Semantic UI etc. all work that way and I've never encountered an issue like this one before ...

**Comment by Caleb-Ellis** [comment] 2018-03-14 09:58
Hi @pojntfx!

No you're not doing anything wrong - the problem is that the version you have of `vanilla-framework-react` doesn't have the Notification component yet! And many others too, since the last release was December last year. We've yet to automate releasing the package, so for now until the near-ish future I would recommend assuming some things in the npm package are missing from this repo. Anyway, I'll release 0.1.3 shortly and write up some release notes so everyone's on the same page.

Closing for now (but reopen if you still have issues with 0.1.3!)

**Closed by Caleb-Ellis** 2018-03-14 09:58 UTC

**Comment by pojntfx** [comment] 2018-03-14 22:03
@Caleb-Ellis Thanks for pointing that out, I did not think of that ;)
